---
- name: Add the group kafka.
  group:
    name: '{{ kafka_arg.user }}'

- name: Add the user kafka.
  user:
    name: '{{ kafka_arg.user }}'
    comment: '{{ kafka_arg.user }}'
    group: '{{ kafka_arg.user }}'
    home: '{{ kafka_path }}/kafka'

- name: Install Apache Kafka {{ kafka_version }} Core.
  unarchive:
    src: '{{ kafka_soft_url }}/apache/kafka/{{ kafka_version }}/kafka_2.12-{{ kafka_version }}.tgz'
    dest: '{{ kafka_path }}/kafka'
    owner: '{{ kafka_arg.user }}'
    group: '{{ kafka_arg.user }}'
    exclude: '{{ kafka_exclusions }}'
    extra_opts: [--strip-components=1]
    remote_src: 'yes'
    validate_certs: 'no'
  register: kafka_update
  until: kafka_update is succeeded
  retries: 3
  delay: 5

- name: Install Kafka support binary package.
  copy:
    src: '{{ item }}'
    dest: '{{ kafka_path }}/kafka/bin/'
    owner: '{{ kafka_arg.user }}'
    group: '{{ kafka_arg.user }}'
    mode: '0750'
  loop: '{{ kafka_support_binary }}'

- name: Install Kafka support JAR package.
  copy:
    src: '{{ item }}'
    dest: '{{ kafka_path }}/kafka/libs/'
    owner: '{{ kafka_arg.user }}'
    group: '{{ kafka_arg.user }}'
    mode: '0644'
  loop: '{{ kafka_support_jars }}'
