---
- name: Sets Zookeeper node variables for role dependencies.
  set_fact:
    kafka_zoo_servers: '{{ kafka_servers }}'
  when:
    - kafka_zoo_dept | bool

- name: Include tasks for specific OS.
  include: '{{ ansible_os_family }}.yml'

- name: Include firewall tasks.
  include: 'firewall.yml'

- name: Kafka installation.
  include: 'install.yml'

- name: Kafka configuration.
  include: 'configureation.yml'

- name: Reload the Kafka service.
  shell: echo ''
  notify: 'Ensure kafka service is enabled'
  when: kafka_config_update is changed or kafka_systemd_update is changed or kafka_jaas_update is changed

- name: Force the handler to run immediately.
  meta: flush_handlers

- name: Include Prometheus exporter tasks.
  include: 'exporter.yml'
  when: exporter_is_install

- name: Registered with HashiCorp Consul.
  include: 'register.yml'
  when: 
    - exporter_is_install | bool
    - consul_public_register | bool

- name: Kafka Eagle installation.
  include: 'eagle.yml'
  when:
    - kafka_eagle_is_install | bool
    - kafka_servers[0] in ansible_default_ipv4.address
