---
- name: Include OS-specific variables
  include_vars: '{{ ansible_os_family }}.yml'

- name: Install the dependent packages
  yum:
    name: '{{ kafka_dependent_packages }}'
    state: 'present'
    validate_certs: 'no'
    disable_gpg_check: 'yes'
  register: yum_status
  until: yum_status is succeeded
  retries: 5
  delay: 2
