---
- name: Enable Kafka service
  systemd:
    name: 'kafka.service'
    enabled: 'yes'
    state: 'restarted'
    daemon_reload: 'yes'
  async: 1
  poll: 0
  listen: Ensure kafka service is enabled
